[package]
name = "voxelland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glam = "0.27.0"
glfw = "0.55.0"
image = "0.25.1"
lockfree = "0.5.1"
num_enum = "0.7.2"
rand = "0.8.5"
